<a href="https://colab.research.google.com/github/darkxenios/MachineLearninghomework/blob/main/Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np              # Массивы (матрицы, векторы, линейная алгебра)
import matplotlib.pyplot as plt # Научная графика
%matplotlib inline
    # Говорим jupyter'у, чтобы весь графический вывод был в браузере, а не в отдельном окне
import pandas as pd             # Таблицы и временные ряды (dataframe, series)
import seaborn as sns           # Еще больше красивой графики для визуализации данных
import sklearn                  # Алгоритмы машинного обучения

## Turkish Crowdfunding Startups

Предположим, что вы хотите изучить крауфандинговые сферу в Турции.

In [36]:
url = "https://raw.githubusercontent.com/darkxenios/MachineLearninghomework/refs/heads/main/BankChurners.csv"
data_raw = pd.read_csv(url)

In [37]:
data_raw.shape

(10127, 23)

In [38]:
data_raw.head()

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,...,12691.0,777,11914.0,1.335,1144,42,1.625,0.061,0.000093,0.99991
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,...,8256.0,864,7392.0,1.541,1291,33,3.714,0.105,0.000057,0.99994
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,...,3418.0,0,3418.0,2.594,1887,20,2.333,0.000,0.000021,0.99998
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,...,3313.0,2517,796.0,1.405,1171,20,2.333,0.760,0.000134,0.99987
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,...,4716.0,0,4716.0,2.175,816,28,2.500,0.000,0.000022,0.99998

In [39]:
data_raw.tail()

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
10122,772366833,Existing Customer,50,M,2,Graduate,Single,$40K - $60K,Blue,40,...,4003.0,1851,2152.0,0.703,15476,117,0.857,0.462,0.000191,0.999810
10123,710638233,Attrited Customer,41,M,2,Unknown,Divorced,$40K - $60K,Blue,25,...,4277.0,2186,2091.0,0.804,8764,69,0.683,0.511,0.995270,0.004729
10124,716506083,Attrited Customer,44,F,1,High School,Married,Less than $40K,Blue,36,...,5409.0,0,5409.0,0.819,10291,60,0.818,0.000,0.997880,0.002118
10125,717406983,Attrited Customer,30,M,2,Graduate,Unknown,$40K - $60K,Blue,36,...,5281.0,0,5281.0,0.535,8395,62,0.722,0.000,0.996710,0.003294
10126,714337233,Attrited Customer,43,F,2,Graduate,Married,Less than $40K,Silver,25,...,10388.0,1961,8427.0,0.703,10294,61,0.649,0.189,0.996620,0.003377

Этот набор данных предоставляет информацию о клиентах для прогнозирования выбытия клиентов по потребительским кредитным картам.

CLIENTNUM: Уникальный идентификатор для каждого клиента. (Целое число)
Attrition_Flag: Флаг, указывающий, закончился ли клиент. (Логическое значение)
Customer_Age: Возраст клиента. (Целое число)
Gender: Пол клиента. (Строка)
Dependent_count: Количество иждивенцев, которые есть у клиента. (Целое число)
Education_Level: уровень образования клиента. (Строка)
Marital_Status: Семейное положение клиента. (Строка)
Income_Category: Категория дохода клиента. (Строка)
Card_Category: Тип карты, которой владеет клиент. (Строка)
Months_on_book: Как долго клиент числится в бухгалтерских книгах. (Целое число)
Total_Relationship_Count: Общее количество отношений клиента с поставщиком кредитной карты. (Целое число)
Months_Inactive_12_mon: Количество месяцев, в течение которых клиент был неактивен за последние двенадцать месяцев. (Целое число)
Contacts_Count_12_mon: Количество контактов, которые были у клиента за последние двенадцать месяцев. (Целое число)
Credit_Limit: Кредитный лимит клиента. (Целое число)
Total_Revolving_Bal: Общий возобновляемый баланс клиента. (Целое число)
Avg_Open_To_Buy: Среднее соотношение открытых и закрытых покупок клиента. (Целое число)
Total_Amt_Chng_Q4_Q1: Общая сумма изменилась с четвертого по первый квартал. (Целое число)
Total_Trans_Amt: Общая сумма транзакции. (Целое число)
Total_Trans_Ct: Общее количество транзакций. (Целое число)
Total_Ct_Chng_Q4_Q1: Общее количество изменилось с четвертого квартала на первый. (Целое число)
Avg_Utilization_Ratio: Средний коэффициент использования клиентов. (Целое число)